config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  #devise_for :admins

  #root to: 'app#index' #トップランディングページ
  get 'app' => 'app#index'
  get 'it' => 'it#index'

  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/contact' => 'contact#index'
  post '/confirm' => 'contact#confirm'
  post '/thanks' => 'contact#thanks'

  get 'recruits' => 'recruits#index'
  post 'recruits/confirm' => 'recruits#confirm'
  post 'recruits/thanks' => 'recruits#thanks'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :company, #会社名
                :name, #名前
                :tel, #電話番号
                :email, #メールアドレス
                :address, #住所
                :project, #プロジェクト名
                :skill, #必要スキル選択
                :skill_other, #必要スキルその他
                :start, #開始予定時期
                :period, #契約予定期間
                :period_select, #
                :remarks #備考

  validates :company, {presence: true}
  validates :name, {presence: true}
  validates :tel, {presence: true}
  validates :email, {presence: true}
  validates :address, {presence: true}
  validates :skill, {presence: true}
  validates :start, {presence: true}
  validates :period, {presence: true}
  validates :period_select, {presence: true}

  @@SkillLists = [
    ["HTML","HTML"],
    ["CSS","CSS"],
    ["javascript","javascript"],
    ["jQuery","jQuery"],
    ["Ruby on Rails","Ruby on Rails"],
    ["PHP","PHP"],
    ["MySQL","MySQL"],
    ["JAVA","JAVA"],
    ["Swift","Swift"],
    ["Python","Python"]
  ]

  def self.SkillLists
    @@SkillLists
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :file, ImagesUploader

  def to_meta_tags
  {
    title: title,
    keyword: keyword,
    description: description
  }
  end
end

app/models/recruit.rb
class Recruit
  include ActiveModel::Model
  attr_accessor :company, #会社名
                :name, #名前
                :tel, #電話番号
                :email, #メールアドレス
                :address, #住所
                :business, #事業内容
                :start, #開始予定時期
                :period, #契約予定期間
                :period_select, #契約予定期間
                :remarks, #備考
                :option

  validates :company, {presence: true}
  validates :name, {presence: true}
  validates :tel, {presence: true}
  validates :email, {presence: true}
  validates :address, {presence: true}
  validates :business, {presence: true}
  validates :start, {presence: true}
  validates :period, {presence: true}
  validates :period_select, {presence: true}

  @@OptionLists = [
    ["リスト制作","リスト制作"],
    ["スクリプト構成","スクリプト構成"],
    ["ターゲット選定","ターゲット選定"],
    ["監視委託","監視委託"]
  ]

  def self.OptionLists
    @@OptionLists
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  layout "app"
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  layout "it"
  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def confirm
    @contact = Contact.new(contact_params)
    @contact.skill = params[:contact][:skill]
    if @contact.valid?
      render :action =>  'confirm'
    else
      render :action => 'index'
    end
    #binding.pry
  end

  def thanks
    @contact = Contact.new(contact_params)
    @contact.skill = params[:contact][:skill]
    ContactMailer.received_email(@contact, @contact.skill).deliver
  end

  private
  def contact_params
    params.require(:contact).permit(
                    :company, #会社名
                    :name, #名前
                    :tel, #電話番号
                    :email, #メールアドレス
                    :address, #住所
                    :project, #プロジェクト名
                    :skill, #必要スキル選択
                    :skill_other, #必要スキルその他
                    :start, #開始予定時期
                    :period, #契約予定期間
                    :period_select, #
                    :remarks #備考
    )
  end
end

app/controllers/it_controller.rb
class ItController < ApplicationController
  layout "it"
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_admin!, except: [:index, :show]
  def index
    #@type = params[:type]
    @posts = Post.order(created_at: "DESC").page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
     redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  private
  def post_params
    params.require(:post).permit(
      :title, #タイトル
      :file,  #写真
      :choice,  #カテゴリー
      :keyword, #キーワード
      :description, #説明
      :body #本文
      )
  end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  layout "app"
  def index
    @recruit = Recruit.new
    render :action => 'index'
  end

  def confirm
    @recruit = Recruit.new(recruit_params)
    @recruit.option = params[:recruit][:option]
    if @recruit.valid?
      render :action =>  'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @recruit = Recruit.new(recruit_params)
    @recruit.option = params[:recruit][:option]
    RecruitMailer.received_email(@recruit, @recruit.option).deliver
  end

  private
  def recruit_params
    params.require(:recruit).permit(
                    :company, #会社名
                    :name, #名前
                    :tel, #電話番号
                    :email, #メールアドレス
                    :address, #住所
                    :business, #事業内容
                    :start, #開始予定時期
                    :period, #契約予定期間
                    :period_select, #契約予定期間
                    :option, #オプション希望
                    :remarks #備考
    )
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def default_meta_tags
    {
    	title:"<%= yield(:title) || 'テレアポ代行なら中小企業専門の『アポ匠』' %>",
    	description: "中小企業専門のアポ代行・営業アウトソーシングなら『アポ匠』！自社の得意なジャンルをとことん極めたからこそ出来る徹底したリソース・マネジメントで貴社のアポ代行を承ります。",
    	keywords: "アポ代行,テレアポ 代行,営業　アウトソーシング,新規 顧客 獲得",
        canonical: request.original_url,  # 優先されるurl
        charset: "UTF-8"
    }
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/it_helper.rb
module ItHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/app/index.html.slim
- set_meta_tags  title: 'テレフォンアポインターのフリーランスへの業務依頼なら『テレアポエージェンシー』'
- set_meta_tags  keyword: 'テレアポ フリーランス,営業代行 フリーランス,テレアポ　代行,テレアポ　格安'
- set_meta_tags  description: 'テレフォンアポインターのフリーランスへの業務依頼なら『テレアポエージェンシー』。経験のあるフリーランスや実際のテレアポ会社で稼働する人材に労力の高いテレアポ業務を委託出来ます。'

/#トップ
br
.back-image-app
  .row
    .col-xs-12
      br
      .front-title
        | リモートの不安を一掃しメリットへ！
        br
        | フリーランス・業務委託でのテレアポ単発委託なら
        br
      .main-title
        | 『テレアポエージェンシー』
      .after-title.hidden-xs
          | 最短１０時間〜
      br
      .box2
        p
          | 顧客満足度96.5%

br
br
.row
  .col-sm-12.center
    =link_to "/recruits", :target=>["_blank"]   do
      =image_tag 'question2.gif', width: '70%', class: 'center'

br
hr.line
br


/# Trouble
.top-wrapper
  h2.heading
    strong
      | テレアポエージェンシー
    | ってどんなサービス？
  br
  br
  h6.heading
    | テレアポエージェンシーは仕事を探しているテレフォンアポインターとインサイドセールスを外注したい企業をマッチングする仲介マッチングサービスです。人材不足と言われる世の中、営業セール人材は特に人材不足に苦しんでいます。そんな既に経験・ノウハウのある即戦力人材を単発でご紹介させて頂くサービスです。
  br
  br
  .row.center
    .col-sm-1
    .col-sm-3
     = image_tag "istockphoto.jpg", width:"100%"
     p 企業
    .col-sm-4
     = image_tag "match.png", width:"80%"
    .col-sm-3
     = image_tag "693.jpg", width:"100%"
     p フリーランス・業務委託
    .col-sm-1
    br
    br

br
hr.line
br


/# Trouble
.top-wrapper
  h2.heading
    strong
      | こんなお悩み
    | ありませんか？
  br
  br
  h6.heading
    | 時代の最先端を行くIT業界。そんな業界だからこそ、まだまだ人材は不足しています。慢性的な悩みから季節需要迄、様々なお悩みがあるのではないでしょうか？
  .row
    .col-sm-1
    br
    br
    .col-sm-4.center.visible-md
      br
      br
      = image_tag "distress.jpg"
    br
    .col-sm-1
    .col-sm-6
       p
         strong
           | ☑︎
         |  自社で電話する営業ノウハウがない
         br
         b.h4
         strong
           | ☑︎
         |  電話スタッフを応募してもなかなか集まらない
         br
         b.h4
         strong
           | ☑︎
         |  テレアポスタッフはすぐに退職してしまう
         br
         b.h4
         strong
           | ☑︎
         |  即戦力のスキルの高い人材にアポを委託したい
         br
         b.h4
         strong
           | ☑︎
         |  アポ会社に委託すると高額で予算が合わない
         br
         b.h4
         strong
           | ☑︎
         |  時間単位で業務委託したい
         b.h4


br
hr.line
br

/# push font
h2.push
   span
     | お任せ下さい！テレアポエージェンシーが
     br
     | あなたに適した人材をご紹介します！

br

/# inquiry image
.row
  .col-sm-12.center
    =link_to "/recruits", :target=>["_blank"]   do
      =image_tag 'question2.gif', width: '70%', class: 'center'

br
hr.line
br

/# push font
h2.push
   span
     | テレアポエージェンシーをご利用頂く
     br
     | メリットをご紹介！

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    strong
      | 時給単位で
    | プロに委託出来る
  br
  br
  h6.heading
    | テレアポエージェンシーは最短5時間より、テレアポのフリーランスにお仕事を業務委託出来ます。テストマーケティングの実施はもちろん、未経験からの研修不要なので即戦力として稼働出来ます。
  br
  br
  .row
   .col-sm-3
   .col-sm-6
     = image_tag "28-1.jpg", width:"100%"
   .col-sm-3

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    |  雇用ではないため
    strong
      |  面倒な手続きはゼロ！
  br
  br
  h6.heading
    | 雇用契約ではなく、フリーランスとの業務委託契約となります。そのため面倒な手続きは一切不要でお仕事に対して対価をお支払いするだけ。
  br
  br
  .row
   .col-sm-3
   .col-sm-6
     = image_tag "akusyu.jpg", width:"100%"
   .col-sm-3

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    | 電話のプロが運営元なので
    strong
      | 成約率が高い
  br
  br
  h6.heading
    | テレアポエージェンシーはテレマーケティング業界ではNo.1の実績を残す企業。そのため必要に応じたトークスクリプトのサポートを行うこともできるため、通常の企業に委託するより成約率が高くなります。
  br
  br
  .row
   .col-sm-3
   .col-sm-6
     = image_tag "usp1.jpg", width:"100%"
   .col-sm-3

br
hr.line
br

/# push font
h2.push
   span
     | テレアポノウハウのない会社も安心
     br
     | 充実オプションサポート

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    strong
      | 超高品質なリストを
    | 都度発注出来る
  br
  br
  h6.heading
    | テレアポにとって一番重要なのはリスト。ITプログラミングを活用し、常に最新のリストを抽出しているテレアポエージェンシーなら『取れるリスト』を制作サポート。
  br
  br
  .row
   .col-sm-3
   .col-sm-6
     = image_tag "28-1.jpg", width:"100%"
   .col-sm-3

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    | アウトバウンドに適した
    strong
      | 抜群のターゲティング選定！
  br
  br
  h6.heading
    | テレアポエージェンシーはターゲティング選定に抜群の定評があります。マーケティングのプロが商材に特化した市場選定を行い、アポ率向上を目指します。
  br
  br
  .row
   .col-sm-3
   .col-sm-6
     = image_tag "usp3.jpg", width:"100%"
   .col-sm-3

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    | 心理学に基づいた
    strong
      | スクリプト作成
  br
  br
  h6.heading
    | トークスクリプトのノウハウをお持ちでない場合、テレアポエージェンシーが代行します。企業様からのヒアリングの上、心理学に基づいたトーク構成を行いアポ獲得率を上昇させます。
  br
  br
  .row
   .col-sm-3
   .col-sm-6
     = image_tag "usp8.jpg", width:"100%"
   .col-sm-3

br
hr.line
br

/# USP Point
.top-wrapper
  h2.heading
    | リモートの不安を解消！
    strong
      | アポインターの監視
  br
  br
  h6.heading
    | リモートは興味があるけど本当に実施しているのか。。。そんな不安をテレアポエージェンシーは一層。独自のCTIシステムを構築し、コール数や必要に応じた録音体制を取っているため、怠慢勤務を無くします。
  br
  br
  .row
   .col-sm-3
   .col-sm-6
     = image_tag "25-1.jpg", width:"100%"
   .col-sm-3

br
hr.line
br

/# price information
.top-wrapper
  h2.heading
    strong
      | テレアポエージェンシーの
    | 料金案内
  br
  br
  h6.heading
    |

table.company.center
  col[width="20%"]
  col[width="30%"]
  tbody
    tr
      th.arrow_box.price colspan="4"
        | 基本料金
    tr
      th.arrow_box
        | 初期費用
      td
        del
           | 50,000円
        span.price
           |  0円
      th.arrow_box
        | システム手数料
      td
        del
           | 25%
        span.price
           |  期間限定20%
    tr
      th.arrow_box
        | 基本稼働費
      td.price
        span
           | 時給4,000円〜
      th.arrow_box
        | 稼働時間
      td.price
        span
           | 5時間〜



table.company.center
  col[width="20%"]
  col[width="30%"]
  tbody
    tr
      th.arrow_box.price colspan="4"
        | オプション
    tr
      th.arrow_box
        | リスト制作費用
      td
        span.price
           | 15,000円〜
      th.arrow_box
        | スクリプト構成
      td
        span.price
           |  24,800円〜
    tr
      th.arrow_box
        | ターゲット選定
      td.price
        span
           | 30,000円〜
      th.arrow_box
        | 監視委託料
      td.price
        span
           | 25,000円〜


.center
  small
    | ※1 能力やスキルを特定する場合、時給単価が変動します。
    br
    | ※2 テレフォンアポイントとなり営業とは異なります。業務範囲のご理解お願いします。

br
hr.line
br

/# inquiry image
.row
  .col-sm-12.center
    =link_to "/recruits", :target=>["_blank"]   do
      =image_tag 'question2.gif', width: '50%', class: 'center'

br
hr.line
br


.top-wrapper
  h2.heading
    strong
      | お申し込み
    | の流れ
  br
  br
  h6.heading
    | お申込みからご紹介迄の流れをご紹介致します。既に人材が埋まっている場合、ご紹介が出来ない場合もございますので、お早目にご相談頂くことをおすすめ致します。

.row
 .col-md-6
   .kokuban-t3
    span.title-t3> ❶お申込みフォームより送信
    | 人材の必要な時期やスキル等、ヒアリング項目等を埋めてお申込みフォームを送信してください。
 .col-md-6
   .kokuban-t3
    span.title-t3> ❷弊社で人材にコンタクト（１〜３営業日）
    | 必要な人材が居るかどうかを弊社にて確認し、必要なフリーランスが適合したら御社にスキルシートのご紹介を致します。
.row
 .col-md-6
   .kokuban-t3
    span.title-t3> ❸業務開始日程を調整
    | 必要に応じてインターネット画面を通じて面談を行い、業務開始日程を決定します。
 .col-md-6
   .kokuban-t3
    span.title-t3> ❹業務を開始し、毎月月末に請求書発行
    | 業務を開始していきます。やりとりについては指定のチャットとカレンダーを活用し、毎月月末に請求書を発行します。

br
hr.line
br


/# push font
h2.push
   span
     | ご好評のより人材が埋まりやすくなっております。
     br
     | お早めにお問い合わせください。


br
.row
  .col-sm-12.center
    =link_to "/recruits", :target=>["_blank"]   do
      =image_tag 'question2.gif', width: '70%', class: 'center'

app/views/contact/confirm.html.slim
br
  =image_tag 'contact.gif', width: '100%'


= form_for(@contact, url: { action: :thanks }) do |f|
  .tops-wrapper
    h2.heading
      span> お問い合わせ内容確認
      | フォーム
    table.company
      colgroup
        col width="10%" /
        col width="20%" /
        col width="70%" /
      tr
        td
          strong.label 必須
        td.arrow_box
          | 会社名
        td
          = f.hidden_field :company
          = @contact.company
      tr
        td
          strong.label 必須
        td.arrow_box
          | 担当者名
        td
          = f.hidden_field :name
          = @contact.name
      tr
        td
          strong.label 必須
        td.arrow_box
          | 電話番号
        td
          = f.hidden_field :tel
          = @contact.tel
      tr
        td
          strong.label 必須
        td.arrow_box
          | メールアドレス
        td
          = f.hidden_field :email
          = @contact.email
      tr
        td
          strong.label 必須
        td.arrow_box
          | 住所
        td
          = f.hidden_field :address
          = @contact.address
      tr
        td
          strong.label.label-blue 任意
        td.arrow_box
          | プロジェクト名
        td
          = f.hidden_field :project
          = @contact.project
      tr
        td
          strong.label 必須
        td.arrow_box
          | 必要スキル
        td
          = f.hidden_field :skill
          = @contact.skill.inspect
      tr
        td
          strong.label.label-blue 任意
        td.arrow_box
          | 必要スキルその他
        td
          = f.hidden_field :skill_other
          = @contact.skill_other
      tr
        td
          strong.label 必須
        td.arrow_box
          | 開始予定時期
        td
          = f.hidden_field :start
          = @contact.start
      tr
        td
          strong.label 必須
        td.arrow_box
          | 契約予定期間
        td
          = f.hidden_field :period
          = @contact.period
          = f.hidden_field :period_select
          = @contact.period_select
      tr
        td
          strong.label.label-blue 任意
        td.arrow_box
          | その他備考
        td
          = f.hidden_field :remarks
          = @contact.remarks
      tr
        td colspan="3"
          = f.submit "確認"

app/views/contact/index.html.slim
= form_for(@contact, url: { action: :confirm }) do |f|
  - if @contact.errors.any?
    strong 入力内容にエラーがあります
    ul
      - @contact.errors.each do |attr, msg|
        li= msg

  =image_tag 'contact.gif', width: '100%'

  .tops-wrapper
    h1.headline-first
      span> お問い合わせ
      | フォーム
    br
    table.company
      colgroup
        col width="10%"
        col width="20%"
        col width="70%"
      tr
        td
          strong.label 必須
        td.arrow_box
          | 会社名
        td
          = f.text_field :company
      tr
        td
          strong.label 必須
        td.arrow_box
          | 担当者名
        td
          = f.text_field :name
      tr
        td
          strong.label 必須
        td.arrow_box
          | 電話番号
        td
          = f.text_field :tel
      tr
        td
          strong.label 必須
        td.arrow_box
          | メールアドレス
        td
          = f.email_field :email
      tr
        td
          strong.label 必須
        td.arrow_box
          | 住所
        td
          = f.text_field :address
      tr
        td
          strong.label.label-blue 任意
        td.arrow_box
          | プロジェクト名
        td
          = f.text_field :project
      tr
        td
          strong.label 必須
        td.arrow_box
          | 必要スキル
        td.center
         .row
          .col-xs-6.center
            = f.collection_check_boxes :skill, Contact.SkillLists, :first, :first, multiple: true
      tr
        td
          strong.label.label-blue 任意
        td.arrow_box
          | 必要スキルその他
        td
          = f.text_field :skill_other
      tr
        td
          strong.label 必須
        td.arrow_box
          | 開始予定時期
        td
          = f.date_field :start
      tr
        td
          strong.label 必須
        td.arrow_box
          | 契約予定期間
        td
          = f.number_field :period
          br
          br
          = f.select(:period_select, [ \
          ["選択してください","選択してください"],
          ["時間","時間"],
          ["日","日"],
          ["ヶ月","ヶ月"],
          ["未定","未定"],
          ])
      tr
        td
          strong.label.label-blue 任意
        td.arrow_box
          | その他備考
        td
          = f.text_area :remarks
      tr
        td colspan="3"
          = f.submit "確認"

app/views/contact/thanks.html.slim
br
=image_tag 'contact.gif', width: '100%'

.tops-wrapper.center
h1.headline  お問い合わせ頂きありがとうございました。

p
  | 確認後、担当者よりご連絡させて頂きます。
p
   = link_to "トップページへ戻る", "/it"
br
br


script[async src="https://www.googletagmanager.com/gtag/js?id=AW-858090558"]
script
  |  window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-858090558');
script
  |  gtag('event', 'conversion', {'send_to': 'AW-858090558/NETyCM_wzKoBEL7YlZkD'});

app/views/layouts/_head.html.slim
meta[charset="uft-8"]
meta[http-equiv="X^UA-Compatible" content="IE=edge"]
meta[name="viewport" content="width=device-width, initial-scale=1,0, initial-scale=1, shrink-to-fit=no"]
= csrf_meta_tags
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= stylesheet_link_tag rel="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
script[src="https://ajax.googleapis.com/js/jquery-3.3.1/slim.min.js"]
script[src="https://ajax.googleapis.com/js/bootstrap.bundle.min.js"]
script[src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"]
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
= display_meta_tags(default_meta_tags)
= favicon_link_tag('favicon.ico')
javascript:
  | fbq('track', 'ViewContent');
  script[async src="https://www.googletagmanager.com/gtag/js?id=G-XV2PH7CLRR"]
  script
    |  window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-XV2PH7CLRR'); 

app/views/layouts/app.html.slim
doctype html
html
  head
      = render template: 'layouts/_head.html.slim'
  header
      .row.header
        .col-xs-12
            p　　 即戦力のテレフォンアポインターを時間単位で活用するなら


  body
    p.notice
      = notice
    p.alert
      = alert
    main
      .bread
        = render_breadcrumbs separator: ' > '
      = yield

app/views/posts/index.html.slim
- set_meta_tags  title: '助成金・補助金をどこよりも詳しく知るなら｜SMART Documentカテゴリー一覧'
- set_meta_tags  keyword: '助成金 一覧,補助金 一覧'
- set_meta_tags  description: '助成金・補助金をどこよりも詳しく知るならSMART Document'

.tops-wrapper
  .row
    .col-sm-12
      h1.headline
        | 新着記事
      - @posts.each do |post|
        .row
          .col-sm-5
            = image_tag post.file.to_s, width:"100%", class:"post-space"
          .col-sm-7.post-base
            .post-title
              = link_to post.title, post_path(post)
            .post-description
              = post.description.html_safe
              - if admin_signed_in?
                = link_to '編集  ', edit_post_path(post), class: 'command'
                = link_to '  削除',
                 			            	post_path(post),
                 			            	method: :delete,
                 			            	class: 'command',
                 			            	data: { confirm: '本当に削除しますか？'}
        br
        hr
      = paginate @posts
  